#!/usr/bin/env python3
"""Generate scripts/seed_recipes.sql from data/recipes.json.

Usage:
    python scripts/generate_seed_sql.py

The generated SQL uses ON CONFLICT ... DO UPDATE so it is idempotent
and safe to re-run against an existing database.
"""

import json
import os
import sys
from pathlib import Path

# Ensure project root is on sys.path so we can import app modules
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DEFAULT_HOUSEHOLD_ID = "00000000-0000-0000-0000-000000000001"
RECIPES_FILE = ROOT / "data" / "recipes.json"
OUTPUT_FILE = ROOT / "scripts" / "seed_recipes.sql"


def _pg_literal(value: object) -> str:
    """Render a Python value as a safe PostgreSQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        # Escape single quotes by doubling them
        escaped = value.replace("'", "''")
        return f"'{escaped}'"
    if isinstance(value, (list, dict)):
        escaped = json.dumps(value, ensure_ascii=False).replace("'", "''")
        return f"'{escaped}'::jsonb"
    return f"'{str(value)}'"


def _pg_text_array(lst: list[str]) -> str:
    """Render a list of strings as a PostgreSQL TEXT[] literal."""
    if not lst:
        return "ARRAY[]::TEXT[]"
    items = ", ".join(f"'{s.replace(chr(39), chr(39)+chr(39))}'" for s in lst)
    return f"ARRAY[{items}]"


def generate(recipes_file: Path, output_file: Path) -> None:
    print(f"Reading {recipes_file} …")
    with open(recipes_file) as f:
        data = json.load(f)

    recipes = data.get("recipes", [])
    print(f"Found {len(recipes)} recipes.")

    lines: list[str] = []
    lines.append("-- Auto-generated by scripts/generate_seed_sql.py")
    lines.append("-- Do not edit manually — re-run the script to regenerate.")
    lines.append("")
    lines.append("-- Ensure pgcrypto is available for gen_random_uuid()")
    lines.append("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    lines.append("")
    lines.append("-- Default household")
    lines.append(
        f"INSERT INTO households (id, name) "
        f"VALUES ('{DEFAULT_HOUSEHOLD_ID}', 'Default') "
        f"ON CONFLICT (id) DO NOTHING;"
    )
    lines.append("")

    skipped = 0
    for raw in recipes:
        # Normalise nutrition — handle both flat and nested formats
        if "nutrition_per_serving" in raw:
            nutrition = raw["nutrition_per_serving"]
        else:
            nutrition = {
                "calories": raw.get("calories_per_serving", 0),
                "protein": raw.get("protein_per_serving", 0.0),
                "carbs": raw.get("carbs_per_serving", 0.0),
                "fat": raw.get("fat_per_serving", 0.0),
            }

        recipe_id = raw.get("id", "")
        name = raw.get("name", "")
        if not recipe_id or not name:
            skipped += 1
            continue

        servings = int(raw.get("servings", 4))
        prep = int(raw.get("prep_time_minutes", 0))
        cook = int(raw.get("cook_time_minutes", 0))
        tags = list(raw.get("tags", []))
        ingredients = raw.get("ingredients", [])
        instructions = raw.get("instructions", [])
        source_url = raw.get("source_url")
        image_url = raw.get("image_url")
        reheats_well = bool(raw.get("reheats_well", False))
        stores_days = int(raw.get("stores_days", 0))
        packs_well = bool(raw.get("packs_well_as_lunch", False))

        nutrition_lit = _pg_literal(nutrition)
        tags_lit = _pg_text_array(tags)
        ingredients_lit = _pg_literal(ingredients)
        instructions_lit = _pg_literal(instructions)
        source_url_lit = _pg_literal(source_url)
        image_url_lit = _pg_literal(image_url)
        reheats_lit = "TRUE" if reheats_well else "FALSE"
        packs_lit = "TRUE" if packs_well else "FALSE"
        name_lit = _pg_literal(name)
        id_lit = _pg_literal(recipe_id)

        lines.append(
            f"INSERT INTO recipes "
            f"(id, household_id, name, servings, prep_time_minutes, cook_time_minutes, "
            f"nutrition, tags, ingredients, instructions, source_url, image_url, "
            f"reheats_well, stores_days, packs_well_as_lunch) "
            f"VALUES ("
            f"{id_lit}, '{DEFAULT_HOUSEHOLD_ID}', {name_lit}, {servings}, {prep}, {cook}, "
            f"{nutrition_lit}, {tags_lit}, {ingredients_lit}, {instructions_lit}, "
            f"{source_url_lit}, {image_url_lit}, {reheats_lit}, {stores_days}, {packs_lit}"
            f") ON CONFLICT (id) DO UPDATE SET "
            f"name = EXCLUDED.name, "
            f"servings = EXCLUDED.servings, "
            f"prep_time_minutes = EXCLUDED.prep_time_minutes, "
            f"cook_time_minutes = EXCLUDED.cook_time_minutes, "
            f"nutrition = EXCLUDED.nutrition, "
            f"tags = EXCLUDED.tags, "
            f"ingredients = EXCLUDED.ingredients, "
            f"instructions = EXCLUDED.instructions, "
            f"source_url = EXCLUDED.source_url, "
            f"image_url = EXCLUDED.image_url, "
            f"reheats_well = EXCLUDED.reheats_well, "
            f"stores_days = EXCLUDED.stores_days, "
            f"packs_well_as_lunch = EXCLUDED.packs_well_as_lunch;"
        )

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(recipes) - skipped} recipe inserts to {output_file}")
    if skipped:
        print(f"Skipped {skipped} recipes with missing id or name.")


if __name__ == "__main__":
    generate(RECIPES_FILE, OUTPUT_FILE)
